### ISSUE TITLE
Docker images keep restarting

### ISSUE THREAD

**Issue by jlaguma** [ONLYOFFICE/DocSpace#1706]
After build/build.backend.docker.sh script on Ubuntu Server 22.04, everything looking good, but docker containers keep restarting.
The "docker logs d0ac597f70ae" shows the following error:
`Unhandled exception. System.InvalidOperationException: The type 'ASC.FederatedLogin.LoginProviders.ZoomLoginProvider, ASC.FederatedLogin' could not be found. It may require assembly qualification, e.g. "MyType, MyAssembly".
   at Autofac.Configuration.Core.ConfigurationExtensions.GetType(IConfiguration configuration, String key, Assembly defaultAssembly)
   at Autofac.Configuration.Core.ComponentRegistrar.RegisterConfiguredComponents(ContainerBuilder builder, IConfiguration configuration)
   at Autofac.Configuration.Core.ConfigurationRegistrar.RegisterConfiguration(ContainerBuilder builder, IConfiguration configuration)
   at Autofac.Configuration.ConfigurationModule.Load(ContainerBuilder builder)
   at Autofac.Module.Configure(IComponentRegistryBuilder componentRegistry)
   at Autofac.Core.Registration.ModuleRegistrar.<.ctor>b__1_0(IComponentRegistryBuilder reg)
   at Autofac.ContainerBuilder.Build(IComponentRegistryBuilder componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProviderFactory.CreateServiceProvider(ContainerBuilder containerBuilder)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<Main>$(String[] args) in /app/onlyoffice/src/products/ASC.People/Server/Program.cs:line 61
   at Program.<Main>(String[] args)
Aborted (core dumped)`

Any tips on how to fix this?

**Comment by Carazyda** [comment]
Hello @jlaguma Is your problem still persisting? Please try it on the latest version of Docspace.
