### ISSUE TITLE
DocSpace enterprise not triggering automatic backups

### ISSUE THREAD

**Issue by Irdiism** [ONLYOFFICE/DocSpace#1828]
We have been using DocSpace for a couple of months now, and we had this issue in the beginning where automatic backups would not trigger, but somehow it started working, and we let it go. It seems that 3 days ago, after more than a month working, without us doing any changes it stopped working again. 

Any idea why this might happen and how to fix it? 

Got this log trace from backup-background.log but can not figure whats going on.

`2024-08-23 11:01:31,103|ERROR|[121]|ASC.Core.Common.Hosting.RegisterInstanceWorkerService - Critical error forced worker to shutdown|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ASC.Core.Common.Hosting.RegisterInstanceWorkerService1.ExecuteAsync(CancellationToken stoppingToken)
2024-08-23 11:01:31,108|ERROR|[49]|ASC.Core.Common.Hosting.RegisterInstanceWorkerService - Critical error forced worker to shutdown|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ASC.Core.Common.Hosting.RegisterInstanceWorkerService1.ExecuteAsync(CancellationToken stoppingToken)
2024-08-23 11:01:31,169|WARN|[53]|ASC.EventBus.RabbitMQ.EventBusRabbitMQ - RabbitMQ: model is shutdown: (null)|System.Exception: AMQP close-reason, initiated by Application, code=200, text='Goodbye', classId=0, methodId=0
2024-08-23 11:18:25,164|ERROR|[64]|ASC.Core.Common.Hosting.RegisterInstanceWorkerService - Critical error forced worker to shutdown|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ASC.Core.Common.Hosting.RegisterInstanceWorkerService1.ExecuteAsync(CancellationToken stoppingToken)
2024-08-23 11:18:25,195|ERROR|[67]|ASC.Core.Common.Hosting.RegisterInstanceWorkerService - Critical error forced worker to shutdown|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ASC.Core.Common.Hosting.RegisterInstanceWorkerService1.ExecuteAsync(CancellationToken stoppingToken)
2024-08-23 11:18:25,303|WARN|[67]|ASC.EventBus.RabbitMQ.EventBusRabbitMQ - RabbitMQ: model is shutdown: (null)|System.Exception: AMQP close-reason, initiated by Application, code=200, text='Goodbye', classId=0, methodId=0`

**Comment by Irdiism** [comment]
Update error logs: 

`2024-08-27 09:25:43,074|ERROR|[32]|ASC.EventBus.RabbitMQ.EventBusRabbitMQ - ----- ERROR Processing message "BackupRequestIntegrationEvent { Id = b8c16bd6-12c8-4780-b309-c330f780f092, CreateOn = 8/27/2024 9:25:43 AM, CreateBy = 03f56b9a-f807-486f-b479-67373f3bb537, Redelivered = False, TenantId = 15, StorageType = ThirdPartyConsumer, StorageParams = System.Collections.Generic.Dictionary2[System.String,System.String], IsScheduled = False, BackupsStored = 0, StorageBasePath = , ServerBaseUri = , Dump = False, TaskId = b6a88c94-b093-422a-abec-d9824746a414 }"|ASC.EventBus.Exceptions.IntegrationEventRejectExeption: Exception of type 'ASC.EventBus.Exceptions.IntegrationEventRejectExeption' was thrown.
   at ASC.Data.Backup.IntegrationEvents.EventHandling.BackupRequestedIntegrationEventHandler.Handle(BackupRequestIntegrationEvent event)
   at ASC.EventBus.RabbitMQ.EventBusRabbitMQ.ProcessEvent(String eventName, IntegrationEvent event) in /home/jenkins/workspace/appserver.deb/install/deb/debian/build/server/common/ASC.EventBus.RabbitMQ/EventBusRabbitMQ.cs:line 435
   at ASC.EventBus.RabbitMQ.EventBusRabbitMQ.ProcessEvent(String eventName, IntegrationEvent event) in /home/jenkins/workspace/appserver.deb/install/deb/debian/build/server/common/ASC.EventBus.RabbitMQ/EventBusRabbitMQ.cs:line 410
   at ASC.EventBus.RabbitMQ.EventBusRabbitMQ.Consumer_Received(Object sender, BasicDeliverEventArgs eventArgs) in /home/jenkins/workspace/appserver.deb/install/deb/debian/build/server/common/ASC.EventBus.RabbitMQ/EventBusRabbitMQ.cs:line 279`

**Comment by Carazyda** [comment]
Hello @Irdiism Please let us know if the issue still persists? We have added some fixes for backup service and rabbitmq in previous versions.

**Comment by Irdiism** [comment]
@Carazyda Yes, this is solved. I had commented in the forum and forgot about this issue. This can be closed as solved
